site_name: TechDocs
repo_url: https://github.com/igorbraga13/
site_url: https://igorbraga13.github.io/modeling_guide/

nav: 
  - Modeling Guideline: 
    - ğŸ“ Overview: A_modeling_guideline/A_overview.md
    - ğŸ¯ Problem Understanding: A_modeling_guideline/B_problem_understanding.md
    - ğŸ“Š Data Understanding and Preparation: A_modeling_guideline/C_data_preparation.md
    - ğŸ” Exploratory Data Analysis: A_modeling_guideline/D_eda.md
    - ğŸ› ï¸ Feature Engineering: A_modeling_guideline/E_feature_engineering.md
    - Modeling and Evaluation: A_modeling_guideline/F_model_selection.md
    - ğŸ§  Model Development and Hyperparameter Tuning: A_modeling_guideline/G_model_development.md
    - âœ… Model Validation and Evaluation: A_modeling_guideline/H_validation.md
    - ğŸ’¡ Model Interpretation and Explanability: A_modeling_guideline/I_model_interpretation.md
    - ğŸš€ Deployment and Operationalization: A_modeling_guideline/J_deployment.md
    - ğŸ“ˆ Model Monitoring and Maintenance: A_modeling_guideline/K_monitoring.md
    - âš–ï¸ Governance, Ethical, and Regulatory Considerations: A_modeling_guideline/L_governance.md
    - ğŸ§° Tools, Technologies, and Best Practices: A_modeling_guideline/M_tools.md
    - ğŸ“š Appendix: A_modeling_guideline/N_appendix.md
    - Legado: A_modeling_guideline/modeling_guideline.md

  - Artifacts: 
    - Canvas: B_artifacts/canvas.md
    - Go / No Go: B_artifacts/go_nogo.md
    - Work Instructions: B_artifacts/work_instruction.md
  
  - Patterns:
    - Data Preparation: C_patterns/data_preparation.md
    #- Feature Engineering: feature_engineering.md
    #- Model Evaluation: model_evaluation.md
    #- Model Deployment: model_deployment.md
    #- Model Monitoring: model_monitoring.md
  
  - Statistical Concepts:
    - Correlation: D_statistical_concepts/correlation.md
    - Homoscedasticity: D_statistical_concepts/homoscedasticity.md
    - Outliers: D_statistical_concepts/outliers.md
    - Seasonality: D_statistical_concepts/seasonality.md
    - Trend: D_statistical_concepts/trend.md
    - Volatility: D_statistical_concepts/volatility.md
  
  - Glossary:
      - Bank Context:
          - BNPL: E_glossary/bank_context/bnpl.md
          - CSI: E_glossary/bank_context/csi.md
          - IFRS9: E_glossary/bank_context/ifrs9.md
          - NPL: E_glossary/bank_context/npl.md
          - PDD: E_glossary/bank_context/pdd.md
          - ROI: E_glossary/bank_context/roi.md
          - SLA: E_glossary/bank_context/sla.md
          - TPV: E_glossary/bank_context/tpv.md

  - Models:
    - Application:
      - Onboarding PJ: F_models/application/onboarding_pj.md
    - Behavior: F_models/behavior/behavior.md
    - Collection: 
      - Creli: F_models/collection/creli.md
  
  - Study Notes: G_study_notes/study_notes.md
  
  - Links: H_links/links.md
  
  - Articles: I_articles/articles.md
  
  - References: J_references/references.md

theme:
  name: material
  features:
    #- navigation.expand        # Menus expansÃ­veis
    - navigation.top           # Mostra o menu de navegaÃ§Ã£o no topo tambÃ©m
    - navigation.instant       # NavegaÃ§Ã£o sem recarregar a pÃ¡gina
  palette:
    - scheme: default         # Light mode
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate           # Dark mode
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode